### PR TITLE
Attach the original Jar under a "thin" classifier

### PR DESCRIPTION
**Pull request by pete-woods**
To address #33

### CODE REVIEW

**Review by MikeGoldsmith — APPROVED** [review]
I've been able to test locally and am happy to accept this. Thanks @pete-woods!

**Comment by MikeGoldsmith** [comment]
Strange, the CircleCI build hasn't been triggered correctly. I'll see if I can re-trigger.

**Comment by MikeGoldsmith** [comment]
Can't figure out what's happening with CI. I'll accept the PR and fix up the build on the main repo if needed.

**Comment by pete-woods** [comment]
> Can't figure out what's happening with CI. I'll accept the PR and fix up the build on the main repo if needed.

I'm guessing you have disabled building PRs from forks or something?

**Comment by MikeGoldsmith** [comment]
Yeah, it's possible. I'll take a look.

**Comment by pete-woods** [comment]
There can be good reasons not to, like avoiding giving away deploy credentials.

**Pull request merged**
