### PR TITLE
Additional user agent configuration

### PR DESCRIPTION
**Pull request by christianjank**
This adds a configuration option for the additional user agent string required by the beeline. The change is minimal. The version has been bumped to 1.0.3.

### CODE REVIEW

**Review by maplebed — COMMENTED** [review]
LGTM, will leave for @asdvalenzuela to do the official stamp.

**Review by asdvalenzuela — APPROVED** [review]

**Comment by conormcd** [comment]
👋 It appears that `io.honeycomb.libhoney/libhoney-java-parent` wasn't pushed to Central along with `io.honeycomb.libhoney/libhoney-java` so I _think_ `1.0.3` is busted at the moment. Am I doing something wrong or is it just a missing push?

**Comment by asdvalenzuela** [comment]
@conormcd thanks for letting us know. I will push a new version today that should be correct and include libhoney-java-parent.

**Comment by conormcd** [comment]
@asdvalenzuela Thanks!

**Pull request merged**
